import { layout } from "@d-exclaimation/next";
import "cal-sans";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default layout(({ children }) => {
  return (
    <html
      className="bg-surface-light dark:bg-surface-dark w-full h-full"
      lang="en"
    >
      <body className={`${manrope.className} w-full h-full`}>{children}</body>
    </html>
  );
});
